# Generated by Django 3.2.14 on 2022-08-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='color',
            field=models.CharField(default='Black', max_length=20, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
