# Generated by Django 3.2.14 on 2022-08-30 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_auto_20220829_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='picture',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Picture'),
        ),
    ]
