# Generated by Django 3.2.14 on 2022-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='auxiliary',
            field=models.BooleanField(default=False, verbose_name='Auxiliary'),
        ),
    ]
