# Generated by Django 3.2.14 on 2022-08-03 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StepEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
                ('activity', models.CharField(choices=[('W', 'Walk/Run'), ('S', 'Swim'), ('B', 'Bike')], default='W', max_length=1)),
                ('amount', models.FloatField()),
                ('steps', models.IntegerField()),
                ('valid', models.BooleanField()),
                ('peaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
