# Generated by Django 3.2.14 on 2022-08-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stepentry',
            name='steps',
        ),
    ]
