# Generated by Django 3.2.14 on 2022-08-17 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0003_remove_stepentry_activity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stepentry',
            old_name='amount',
            new_name='steps',
        ),
        migrations.AddField(
            model_name='stepentry',
            name='notes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
