# Generated by Django 3.2.14 on 2022-08-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0004_auto_20220816_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepentry',
            name='steps',
            field=models.IntegerField(),
        ),
    ]
