# Generated by Django 3.2.14 on 2022-09-01 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0010_stepentry_one entry for day in september'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='imperial',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='stepentry',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
