# Generated by Django 3.2.14 on 2022-09-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0012_alter_profile_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='imperial',
            field=models.BooleanField(default=True, help_text='Check means distances are miles, unchecked means kilometers.', verbose_name='USA Units'),
        ),
    ]
