# Generated by Django 4.2.4 on 2023-09-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steps', '0015_alter_stepentry_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fundraising',
            field=models.CharField(choices=[('TSC', "Count my steps towards my group's fundraising"), ('NO', "Do not count my steps towards my group's fundraising. I wish to fundraise separately or do not wish to use my steps to fundraise")], default='TSC', max_length=3),
        ),
    ]
