# Generated by Django 4.2.4 on 2023-08-28 22:49

from django.db import migrations


NEW_FAQS = [
"""<h2>Why do you need my email?</h2>
<p>It allows us to automate password resets, while ensuring no one can steal your login.
We will not mail you except at your request, will never sell your information, and will
delete the emails out of our database after the challenge concludes.</p>
""",
"""<h2>What is the relationship between the MPC Step Challenge and the Team Step Challenge?</h2>
<p>The Team Step Challenge is intended to be an addition to, and aid to participating in, the MPC
Munro Step Challenge, traditionally held every September.  Our Team Step Challenge is, however, 
independently run and not endorsed or sponsored or managed in any way by My Peak Challenge. It is 
quite possible to just do the Munro Step Challenge--or to do just our Team Step Challenge. Personally,
we recommend doing both! Our website aims to make keeping track of your September steps easy, so that 
you or your group administrators can update an MPC affiliated fundraising page, some other fundraising page,
or no fundraising at all.</p>""",
"""<h2>What is the Team Step Challenge?</h2>
<p>All participants are divided evenly between some number of Teams (usually about 8).  Each participant reports the steps they walked each day,
or the minutes they spent on some healthful activity. These are totalled up for the Teams, and we report the running totals a few times a week, with
encouragement and friendly striving.</p>
<p>Everyone who registers with the same Ambassador group will be put on the same team.  This allows Group Admins to encourage and track their members together.</p>""",
"""<h2>What is the MPC Moonro Step Challenge?</h2>
<p>It is a fundraising event run by My Peak Challenge.  It usally involves keeping track of steps done during September.</p>
<p>This year's theme is the Moon!  Other than that, MPC says to stay tuned.</p>"""
]

def add_faqs(apps, schema_editor):
    faq = apps.get_model('faq_page', 'FaqPage')
    for question in NEW_FAQS:
        faq_question = faq(description=question)
        faq_question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faq_page', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_faqs)
    ]
