# Generated by Django 3.2.14 on 2022-08-05 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpc_groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpcAdminRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('primary_group', models.CharField(max_length=60, verbose_name='MPC Group')),
                ('secondary_group', models.CharField(max_length=60, verbose_name='Optional second group')),
            ],
        ),
        migrations.AlterField(
            model_name='mpcgroup',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='Name'),
        ),
    ]
