# Generated by Django 3.2.14 on 2022-08-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpc_groups', '0003_alter_mpcadminregistration_secondary_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='name',
            field=models.CharField(help_text='Enter the name you use in the Ambassador group facebook page.', max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='primary_group',
            field=models.CharField(help_text='The name of your MPC Group, as you wish it to appear.', max_length=60, verbose_name='MPC Group'),
        ),
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='secondary_group',
            field=models.CharField(blank=True, help_text='If you are the admin of another group, you can enter it here and we will try and make sure both are on the same <b>Team</b>', max_length=60, verbose_name='Optional second group'),
        ),
    ]
