# Generated by Django 3.2.14 on 2022-08-15 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpc_groups', '0004_auto_20220804_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mpcgroup',
            name='admin',
            field=models.CharField(default='No Admin', max_length=60, verbose_name='Admin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='name',
            field=models.CharField(help_text='Enter the facebook name you use.', max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='primary_group',
            field=models.CharField(help_text='Enter the name of your Ambassador Group as you wish it to appear.', max_length=60, verbose_name='Ambassador Group'),
        ),
        migrations.AlterField(
            model_name='mpcadminregistration',
            name='secondary_group',
            field=models.CharField(blank=True, help_text='If you are the admin of another group, you can enter it here to request your two groups be on the same Team.', max_length=60, verbose_name='Optional Additional Group'),
        ),
    ]
