# Generated by Django 3.2.14 on 2022-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpc_groups', '0005_auto_20220815_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupModifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modification_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='mpcgroup',
            name='admin',
            field=models.CharField(default='No Admin', max_length=60, verbose_name='Admin'),
            preserve_default=False,
        ),
    ]
