# Generated by Django 3.2.14 on 2022-08-31 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_picture'),
        ('mpc_groups', '0006_auto_20220826_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpcgroup',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
